### ISSUE TITLE
Can't install on CM12

### ISSUE THREAD

**Issue by osmose99** [urandom/gearshift#22]
Can't install on CM12. It says "Application not installed" and when using F-Droid it says "(De-)installation error". I tried on other lollipop ROM and it install correctly.

**Comment by urandom** [comment]
You might get a more verbose error message from logcat when you try to install it

**Comment by osmose99** [comment]
I only sea this in logcat: 01-11 07:56:25.021 D/InstallAppProgress(22832): Installation error code: -18

**Comment by osmose99** [comment]
Just to be sure, my device have enough space on it. But the message seems to be about space left.

**Comment by simba83** [comment]
I have had the same error earlier on cm12 a reboot use to fix it, after that I moved the gearshift app from SD card to internal and everything have been working fine for me.

**Comment by osmose99** [comment]
I am on a nexus 7 8gig. No sdcard. I have been able to  it on my sgs3 by installing it manually in /system/app but it doesn't work on my Nexus.

**Comment by urandom** [comment]
I don't think there's anything I can do from the app's point of view. Might be a bug in the rom

**Comment by osmose99** [comment]
Thanks a lot, I'll open an issue for this rom.

**Comment by qMarcinek** [comment]
I had a similar problem with installing Gear Shift on Lollipop. Fixed this by changing android:installLocation to "auto" in manifest. Is "externalOnly" actually needed?

**Comment by urandom** [comment]
@qMarcinek 
I think it used to be at some point, but who knows. I haven't had a phone with an sd card in a long time. Good call, I'll change that soonish.
