### ISSUE TITLE
Download directories can not be / are not saved

### ISSUE THREAD

**Issue by pgaubatz** [urandom/gearshift#25]
Hi,

on CM12 it's not possible for me to save any download directories for a given connection profile.
When entering or leaving the corresponding activity, logcat tells me the following:
```
W/Resources(25431): Converting to string: TypedValue{t=0x10/d=0x2383 a=-1}
W/Resources(25431): Converting to string: TypedValue{t=0x10/d=0x1f90 a=-1}
W/Resources(25431): Converting to string: TypedValue{t=0x10/d=0x2383 a=-1}
W/Resources(25431): Converting to string: TypedValue{t=0x10/d=0x1f90 a=-1}
```
Does this look suspicious to you?

Cheers,
Patrick

**Comment by OMEN79** [comment]
In download torrent dialog when switching between several profiles recent folders of those profiles are not propagated in folder field

**Comment by urandom** [comment]
> In download torrent dialog when switching between several profiles recent folders of those profiles are not propagated in folder field if selected profile isn't the current one.

In order to get the currently used directories, all the torrents will have to be fetched for each profile. That's quite a bit of network traffic for something that will not provide a lot of gain (once the actual ticket is fixed, the dialog should also show the saved directories). This is why it doesn't show them, and that's by design.

**Comment by OMEN79** [comment]
> In order to get the currently used directories, all the torrents will have to be fetched for each profile. That's quite a bit of network traffic for something that will not provide a lot of gain (once the actual ticket is fixed, the dialog should also show the saved directories). This is why it doesn't show them, and that's by design.

I see, but when switching profiles in the main program window it's OK and there aren't any problems appear

**Comment by urandom** [comment]
> I see, but when switching profiles in the main program window it's OK and there aren't any problems appear

There that's the whole point. You select a profile and you expect to see its torrents, and everything related to it.

When adding a torrent however, that's a lot of extra information for just displaying a bunch of directories for something that you can also change later. The selected profile is something temporary, used for adding the torrent, and not used in any other way, until you properly switch to it.

**Comment by pgaubatz** [comment]
Urandom, is there anything I can do to help you reproducing the bug that I've found?

**Comment by urandom** [comment]
@pgaubatz 
So far I'm not able to reproduce it. And I'm not sure the logcat output you posted was relevant (the directories are not resources, but plain strings). Just to be clear, after you go from the 'directories' screen to the main profile screen, you are pressing the top-left 'done' icon in order to save the changes, including the new directories, correct?

**Comment by pgaubatz** [comment]
@urandom 
Okay... that's interesting. As you can see in the following two screenshots, a "done" icon is never shown on my device:
![1](https://cloud.githubusercontent.com/assets/103894/6244285/95e2cc58-b751-11e4-8a83-cb5a8a350e61.png)
![2](https://cloud.githubusercontent.com/assets/103894/6244286/95e4b298-b751-11e4-9bcd-3d08120e55ae.png)

**Comment by urandom** [comment]
@pgaubatz 
Not this screen. Think of this one as a popup dialog or something. The done icon appears in the parent screen, with the main profile preferences.

**Comment by pgaubatz** [comment]
Ahh... I see. :)
Okay then, saving worked.
I think you can close this bug report!
