### ISSUE TITLE
Drops certain torrents

### ISSUE THREAD

**Issue by lincalinca** [urandom/gearshift#36]
I've been using the newest release for about a month now, but it seems to drop certain torrents when I install them. It seems it's more the magnets than full torrent downloads, but I'm not 100% sure. My Transmission environment was a bit buggy, but using Transdrone, I could see these same torrents, despite missing from my queue in Gearshift. I think it was to do with the folders I had the torrents downloading to, also.

**Comment by urandom** [comment]
Honestly, I can't do anything with such info. What do you mean by "a bit buggy"? Maybe you should fix that first and the problem might go away :) If it doesn't, enable debug logging, send in the resulting logcat, and _maybe_ we might find the problem
