### ISSUE TITLE
Dual sign-in for WAN vs LAN

### ISSUE THREAD

**Issue by lincalinca** [urandom/gearshift#37]
Transdrone, which all in all is an inferior app, has a nifty feature where you can indicate what your LAN SSID is and your transmission's local IP as well as the WAN details, so that it can optimise the use of communication, whether by WAN or LAN depending on availability. I'd like to see this feature, but perhaps even to flesh it out more, to vary the refresh rate over WAN to one interval, and the LAN at a (logically, more frequent) interval.

I realise this is two requests rolled into one.

**Comment by urandom** [comment]
I've opted to only fix your second request. Each profile now defines its own update intervals, thus you can  assign aggressive updates for profiles on the local network, and less aggressive ones over the internet.
