### ISSUE TITLE
Why it is not in the Play store?

### ISSUE THREAD

**Issue by fduraibi** [urandom/gearshift#39]
Hi, I love this application, but I am wondering why it is not in the official Google Play Store?

**Comment by urandom** [comment]
It was removed by Google.

**Comment by fduraibi** [comment]
For what reason? there are many torrent apps in the play store?

I also don't see any conflicting names with other app or games, and there doesn't seem to be a trade mark on that name. Have you tried contacting them again?

**Comment by lincalinca** [comment]
Weird they'd remove this, yet Transdrone is still available. What's the
difference between the two, in terms of what's considered acceptable? The
only reason I keep TD on my phone is that for some reason, GS keeps
dropping off my list of apps (I think it's the launcher that I use is a bit
fickle with non-Play Store apps, so unless it can be put back in the store,
I don't think there's anything which could be done).

**Comment by fduraibi** [comment]
@urandom I suggest that you put it back in the store and try. In the images don't show torrents that are not free to download, instead show things like linux distros and free videos like the Big Buck Bunny so it won't violate the DRM or whatever that might make them remove it.

This is a good app, and it should be available on the play store.

**Comment by mtimvik** [comment]
This app is avaliable in F-Froid, bit not latest version.
