### ISSUE TITLE
Deleting torrents without removing content

### ISSUE THREAD

**Issue by Stygmatik** [urandom/gearshift#40]
Hi there !

I would like first to thank you for this nice piece of software!
Very useful, and perfect design.

I just noticed that, since update 1.X, when you remove a torrent, the content linked to it is also removed.
Before that, we had the possibility to just remove the torrent (.torrent file in fact) from the list of active torrents, but also keeping the content on the transmission host.

Is there an option I'm missing in the settings of the app, or it's not possible anymore? And if so, why?

Thanks again for your time and effort!

Regards

**Comment by urandom** [comment]
The 'remove' dialog provides two options for removal, deleting torrent and data, and only removing the torrent. What you want is already implemented, you just have to avoid pressing 'delete the data'

**Comment by Stygmatik** [comment]
I can indeed confirm that's not the case.
Gear Shift 1.0 from F-Droid.
When I click on 'remove', I got a dialog providing the two following choices:

**Comment by urandom** [comment]
There's also an 'OK' button right next to the cancel button. It's part of android's standard alert dialog. You're not seeing that?

**Comment by Stygmatik** [comment]
Nope, look :o

![screenshot_2015-11-17-08-44-38 1](https://cloud.githubusercontent.com/assets/1180607/11205447/0d53597e-8d08-11e5-872b-4c31230dbfa1.png)

**Comment by urandom** [comment]
maybe its because the string for the left button is too long, if you rotate the phone, does the 3rd button appear?

**Comment by Stygmatik** [comment]
Pppfff, guess what?

That's the problem...

In landscape I can see the three buttons.
In portrait, even if not visible, there is in fact a clickable area
corresponding to the "ok" button.

That wasn't present in version prior to 1.0

What could be done there? Revert to old traduction that wasn't buggy?

Cheers
Le 17 nov. 2015 9:21 AM, "Viktor Kojouharov" <notifications@github.com> a
écrit :

**Comment by urandom** [comment]
The dialogs use google's support library, so that's a bug in it. I guess I'll have to remove the button and add a checkbox instead, which unfortunately will lead to 2 taps if you want to delete a torrent and the data.

**Comment by Orppa** [comment]
Do all the translations also come from the lib? Or could those be shortened, mainly the first, longest one, to keep current way of functioning?

**Comment by Stygmatik** [comment]
A solution could be to have this long message (I didn't find a nice
alternative), displayed on 2 lines in smaller font.

That will lead to 3 buttons with more height.

Could it be possible to fix the width of each of the 3 buttons to 1/3 of
the width of the dialog? Thus, "forcing" the display on many lines if
needed.

Will be less nice, but will be working at least.
Le 17 nov. 2015 4:07 PM, "Viktor Kojouharov" <notifications@github.com> a
écrit :

**Comment by urandom** [comment]
@Orppa the translation of the first button comes from the app. At least the english version is as short as possible while still trying to tell you what it will do. 

@Stygmatik I don't think you get to have any customization options for these buttons

**Comment by Orppa** [comment]
So if current dialog would be kept, all the translations would have to be checked and possibly changed. Maybe it's just easier and safer to think of an alternative way. The one you already suggested, or something else.

Having one extra tap opposed to not having a button visible sounds still better option.

**Comment by Stygmatik** [comment]
I was thinking also about the extra tap.
Could in fact be seen as a security tap for the data also.

Or you could shorten "Supprimer les données" in "Suppr. Donn." Should fit.

Last option: is it possible to have an horizontad scroll of the text (back
and forth) on a button ? To keep a fixed width.

**Comment by urandom** [comment]
The neutral button is now a checkbox. It's default state can be set from the general settings.
