### ISSUE TITLE
Installation Fails on CyanogenMod 12.1

### ISSUE THREAD

**Issue by LibertatisPrius** [urandom/gearshift#42]
I cannot get the latest update (1.0.2] to install. I get to the installation dialog but the installation fails with only the message "app not installed."

I am on a OnePlus One running CyanogenMod 12.1.

**Comment by simba83** [comment]
Try to uninstall and reinstall the app and everything should work. Android bug.

**Comment by LibertatisPrius** [comment]
Thank you; that solved the issue.
