### ISSUE TITLE
Heavy torrents upload problem

### ISSUE THREAD

**Issue by pety3bi** [urandom/gearshift#43]
I'm having issues while uploading huge blu-ray image torrents. It seems to newer upload. Using Transmmision Remote GUI everything is working correctly.

**Comment by simba83** [comment]
I can confirm this issue, im also seeing that Transmission remote gui is faster to add torrents.
I don't know when and why the issue occure.
Maybe pety3bi can add some kind of log when this happens. (only happed a few times here).

**Comment by pety3bi** [comment]
I can add any log, but i need to know what log will help to solve this issue. It's realy annoying to switch from this perfect GUI to others sometimes to add such torrents.

**Comment by urandom** [comment]
it'll probably be easier if you provide a huge torrent, though that might be illegal.

**Comment by pety3bi** [comment]
[http://storage.tver.gq/gearshift/sources.torrent](url)
this is an example torrent (opencv original sources, no seeds), gives the error while trying to add it. Transmission Remote GUI feels good and successfully add it.

**Comment by urandom** [comment]
The issue should now be fixed. It will be part of the next release, whenever that is.
