### ISSUE TITLE
Remove torrent when adding

### ISSUE THREAD

**Issue by simba83** [urandom/gearshift#45]
The remove torrent file when adding a torrent checkbox doesn't seem to work. I check the box but the torrent is still in my android download directory.

**Comment by Orppa** [comment]
Couple of weeks ago it removed the .torrent files for me.

**Comment by simba83** [comment]
Does it still work? Could be my RR rom 6.0.1 security update 1feb 2016 tried both to check and uncheck the checkbox anyone else could confirm?

**Comment by Orppa** [comment]
Just confirmed that it works. The file shouldn't make a difference, but I tried with these:
http://www.jide.com/en/remixos-for-pc#downloadNow

**Comment by simba83** [comment]
Doesn't work here, I exit the app cleared cache, removed settings and tried again didnt work. The app didn't have permission to storage, therefor it couldn't remove the file. It should have been a notification on that though. Everything works good now.
