### ISSUE TITLE
No updates from F-droid

### ISSUE THREAD

**Issue by mtimvik** [urandom/gearshift#46]
I have a message in app(I use 1.0 from F-droid), that new version 1.0.2 is avaliable.
I don't like apps that check updates directly from app. (It is windows way).

Why there is no last version in F-droid?

**Comment by urandom** [comment]
You'll have to ask whoever was responsible for uploading it there in the first place. I don't use F-droid.

**Comment by mtimvik** [comment]
I think you just need to update "versionCode" in build.gradle
