### ISSUE TITLE
Missing filters and strange things with settings in 1.0.3

### ISSUE THREAD

**Issue by pety3bi** [urandom/gearshift#54]
![screenshot_20161113-172153](https://cloud.githubusercontent.com/assets/12010381/20246338/f6a583ba-a9c5-11e6-81ca-50fd59f39d5d.jpg)
![screenshot_20161113-172148](https://cloud.githubusercontent.com/assets/12010381/20246346/fca31624-a9c5-11e6-9a9a-7f799628e775.jpg)

Just downloaded latest release. Asus ze500kl (zenphone lazer), Android 6.0.1.
See the screenshots attached.

**Comment by simba83** [comment]
Same here but if you scroll down on the filters youll see them.

**Comment by pety3bi** [comment]
Confirming, scroll down in both situations shows all. Maybe smth. wrong with "splitter".

**Comment by urandom** [comment]
Look's like something's wrong with the style of the headers. Probably related to the update of the support libraries.

**Comment by pety3bi** [comment]
Hope you can fix it soon, by the way, are other fixes included in this update? I'll check it myself, but i think it would be great to mention it in changes if they are included.

**Comment by bloodbass** [comment]
Same problem. Android 5.1.1.
