### ISSUE TITLE
Allow torrent url

### ISSUE THREAD

**Issue by Haocen** [urandom/gearshift#64]
Allow HTTP/HTTPS url when add a torrent, currently one can only supply magnet Uri.

Note this is supported by transmission back end so no extra effort is needed other than change of the input validation/back end call.

**Comment by urandom** [comment]
@Haocen 
Are we talking about a url to a torrent file, as oppose to uploading the torrent file's contents?

**Comment by Haocen** [comment]
Yes I am. Having to download the torrent first seemed a little inconvenient.
